mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-mysql-user-here
  password: your-mysql-password-here
  host: your-mysql-host-here
  database: your-mysql-database-here

development:
  <<: *mysql_settings

production:
  <<: *mysql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
